### ISSUE TITLE
[FEAT] User, Company, Todo, File entity

### ISSUE THREAD

**Issue by sueelly** [Planner-LifeStock/planner-lifestock-server#20]
# Contents
도메인별로 개발을 진행하니 join되는 entity들에 대해 개발이 불가하여 따로 feature branch를 생성한다.

## Detail
- [ ] User merge
- [ ] Todo merge
- [ ] File entity create
- [ ] Company entity create

## Confirm assignee
(expected) assignee: @sueelly 
- [ ] assignee check

## Check Priority
Expected Priority: HIGH
- [ ] Check the Assignee's Priority (adjust priority if necessary)
- [ ] Check PM(@sueelly)'s Final Priority

## Reference (Optional)
(null)
