### ISSUE TITLE
[FIX] 1차 main api 수정 (company, todo, chart)

### ISSUE THREAD

**Issue by sueelly** [Planner-LifeStock/planner-lifestock-server#36]
# Contents
company, todo, chart CRUD api 에러를 수정한다

## Detail
- [x] chart 개편
- [x] company-chart 연동
- [x] todo-chart 연동

## Confirm assignee
(expected) assignee: @sueelly 
- [x] assignee check

## Check Priority
Expected Priority: Critical
- [x] Check the Assignee's Priority (adjust priority if necessary)
- [ ] Check PM(@sueelly)'s Final Priority

## Reference (Optional)
(null)
